### PR TITLE
Add vector effect attr

### PR DESCRIPTION
**Pull request by ebrillhart**
Addresses issue #238 from the victory repo. Added the vector effect attr to the text element returned by Victory-Label. @paulathevalley let me know whether you think this needs to be applied to other aspects of Victory - when @boygirl and I discussed it we just talked about adding it to victory-label text.

### CODE REVIEW

**Comment by boygirl** [comment]
@ebrillhart we only commit `dist/` for releases. Can you remove it from this PR?

**Comment by ebrillhart** [comment]
@boygirl whoops, removed

**Comment by boygirl** [comment]
@ebrillhart ah, sorry. Remove as in this PR should not include either additions or deletions for anything in `dist/`. Given how minor your other changes are it might be easier to just copy them over to a new branch.

**Comment by ebrillhart** [comment]
@boygirl ah makes sense. will do!

**Comment by paulathevalley** [comment]
@ebrillhart @boygirl I would also consider adding it to the axis ticks, axis lines, and grid lines... essentially anything with a stroke. 

Here is an example of where I added `vector-effect`: 
http://codepen.io/paulathevalley/pen/Ragobo

**Pull request closed without merging**
