### PR TITLE
increasing default font size for victory-label

### PR DESCRIPTION
**Pull request by ebrillhart**
okay, this is the actual pull request for adding the vectorEffect attr to the text element of victory-label

### CODE REVIEW

**Comment by boygirl** [comment]
@ebrillhart I've checked this using `npm link` with VictoryChart, and I see the non-scaling-stroke attr being applied, but the labels still scale to unreadably small sizes :/

**Comment by ebrillhart** [comment]
@boygirl hmm okay I'll figure out how to make that stop happening

**Comment by boygirl** [comment]
@ebrillhart thanks!

**Comment by paulathevalley** [comment]
Oops, found the right PR! 

I think `non-scaling-stroke` only applies to elements with `stroke-width`, so it won’t do anything to `<text>` or `<tspan>` elements. I looked around briefly for trying to pin the font-size of `<tspan>` or `<text>` to a specific size, but the only information I received was that SVGs are scalable by their nature! 

Off the top of my head, alternatives would be setting a min-width to the `<svg>` container or increasing the default font-size so it’s readable for a larger range of widths. 

https://www.w3.org/TR/SVGTiny12/painting.html#NonScalingStroke
https://github.com/FormidableLabs/victory/issues/238

**Comment by ebrillhart** [comment]
okay, for now I'll apply it to grid lines, axes, and tick marks - @boygirl any preference for how we handle text/labels or should we just hold off on that for now?

**Comment by boygirl** [comment]
@ebrillhart prefer increasing the default font size for now.

**Pull request closed without merging**
