### PR TITLE
Voronoi stack

### PR DESCRIPTION
**Pull request by stefvhuynh**
Necessary for https://github.com/FormidableLabs/victory-chart/pull/555.

### CODE REVIEW

**Review by sibelius — APPROVED** [review]

**Comment by f0rr0** [comment]
Why isn't this being merged?

**Comment by sibelius** [comment]
@boygirl can u take a look?

@stefvhuynh can u fix conflicts?

**Comment by f0rr0** [comment]
Could this have anything to do with https://codesandbox.io/s/4z6ww6w7m0

it seems to me that voronoi isn't working as expected with horizontal bars with holes (gantt chart)?

**Comment by boygirl** [comment]
@sibelius @f0rr0 

The corresponding PR in victory-chart has some issues that need to be resolved. @stefvhuynh is off the project, and I've let these two slip through the cracks. Apologies. I will pick these back up next week.

**Comment by sibelius** [comment]
@boygirl tks for the hard work on this package

**Pull request merged**
