### PR TITLE
update react versions, update enzyme

### PR DESCRIPTION
**Pull request by boygirl**
Notes:

No code issues in upgrading to React 16. 

Testing issues as follows:
Upgrading to React 16 requires upgrading to `enzyme@^3.0.0` + `enzyme-adapter-react-16` and configuring an adapter. Hitting in this issue: https://github.com/airbnb/enzyme/issues/1189. The solution looks like it requires including a polyfill for `Set` in our karma config.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
If it helps @boygirl here's what we've got in Radium: https://github.com/FormidableLabs/radium/blob/master/karma.conf.js#L8-L10

(From https://github.com/FormidableLabs/radium/pull/931/files)

**Comment by boygirl** [comment]
@ryan-roemer Thanks! That does help. Should that `core-js` dep end up in `builder-victory-component-dev`?

**Comment by ryan-roemer** [comment]
@boygirl -- Yep! I think so.

**Comment by boygirl** [comment]
Notes: 

```
TypeError: undefined is not an object (evaluating '__WEBPACK_IMPORTED_MODULE_4_react__["PropTypes"].object')
  at /Users/boygirl/formidable/v/victory-core/test/client/main.js:40668
```
results when attempting to configure enzyme from `test/client/main.js`.

**Comment by ryan-roemer** [comment]
@boygirl -- That's a `React.PropTypes` error. There's definitely a problem here: https://github.com/FormidableLabs/victory-core/blob/master/test/client/spec/mock-components.js#L2 that wasn't ported over correctly to `prop-types`.

Worst case, tweak configs and build that webpack config out to disk and inspect the lines errors come from.

**Comment by boygirl** [comment]
Yikes, how'd I miss that?

**Pull request merged**
